# Generated by Django 6.0.7 on 2026-07-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_room_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
