# Generated by Django 6.0.7 on 2026-07-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='pharmacy_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
