# Generated by Django 6.0.7 on 2026-07-11 06:53

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacyprofile_pharmacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='pharmacy_id',
            field=models.CharField(default=core.utils.generate_pharmacy_id, max_length=12, unique=True),
        ),
    ]
