# Generated by Django 6.0.7 on 2026-07-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='duration_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consultation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
