# Generated by Django 6.0.7 on 2026-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_consultation_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lab_test',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pulse_bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
