# Generated by Django 6.0.7 on 2026-07-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
