# Generated by Django 6.0.7 on 2026-07-11 06:44

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor_id',
            field=models.CharField(default=core.utils.generate_doctor_id, max_length=12, unique=True),
        ),
    ]
