# Generated by Django 6.0.7 on 2026-07-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctorprofile_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='degree_certificate',
            field=models.FileField(default='', upload_to='doctor_certificates/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
